In [ ]:
from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/공모전/공모전/BDA/data/칼럼 추출 데이터셋/2024년_1인_관광_칼럼수정.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

data = pd.read_csv(file_path)

In [ ]:
data.columns = data.iloc[1]
data = data.drop(index=[0, 1])
data = data.reset_index(drop=True)

Buffered data was truncated after reaching the output size limit.

In [ ]:
list_col14 = ['D_TRA1_CASE','D_TRA2_CASE','D_TRA3_CASE',
'D_TRA4_CASE',     #0~3
'D_TRA1_1_SPOT',   # 4~9
'D_TRA1_2_SPOT',
'D_TRA1_3_SPOT',
'D_TRA1_4_SPOT',
'D_TRA1_5_SPOT',
'D_TRA1_6_SPOT',
'D_TRA2_1_SPOT',  #10~13
'D_TRA2_2_SPOT',
'D_TRA2_3_SPOT',
'D_TRA2_4_SPOT',
'D_TRA3_1_SPOT',  #14~15
'D_TRA3_2_SPOT',
'D_TRA4_1_SPOT',  #16
'D_TRA1_B7A_1',   # 17~22
'D_TRA1_B7A_2',
'D_TRA1_B7A_3',
'D_TRA1_B7B_1',
'D_TRA1_B7B_2',
'D_TRA1_B7B_3',
'D_TRA2_B7A_1',  # 23~28
'D_TRA2_B7A_2',
'D_TRA2_B7A_3',
'D_TRA2_B7B_1',
'D_TRA2_B7B_2',
'D_TRA2_B7B_3',
'D_TRA3_B7A_1',  # 29~31
'D_TRA3_B7B_1',
'D_TRA3_B7B_2',
'D_TRA4_B7A_1',  #32~33
'D_TRA4_B7B_1',]

data20 = data[list_col14]

In [ ]:
data20.sum()

D_TRA1_CASE           495.0
D_TRA2_CASE            63.0
D_TRA3_CASE             3.0
D_TRA4_CASE             1.0
D_TRA1_1_SPOT    14364600.0
D_TRA1_2_SPOT     3804480.0
D_TRA1_3_SPOT     2053440.0
D_TRA1_4_SPOT      748040.0
D_TRA1_5_SPOT      251560.0
D_TRA1_6_SPOT      113410.0
D_TRA2_1_SPOT     1159990.0
D_TRA2_2_SPOT      356350.0
D_TRA2_3_SPOT       60100.0
D_TRA2_4_SPOT       58100.0
D_TRA3_1_SPOT       98850.0
D_TRA3_2_SPOT       34380.0
D_TRA4_1_SPOT       11010.0
D_TRA1_B7A_1         1185.0
D_TRA1_B7A_2          417.0
D_TRA1_B7A_3           32.0
D_TRA1_B7B_1         2265.0
D_TRA1_B7B_2         1609.0
D_TRA1_B7B_3           73.0
D_TRA2_B7A_1           97.0
D_TRA2_B7A_2           44.0
D_TRA2_B7A_3           10.0
D_TRA2_B7B_1          250.0
D_TRA2_B7B_2          117.0
D_TRA2_B7B_3            6.0
D_TRA3_B7A_1           13.0
D_TRA3_B7B_1           23.0
D_TRA3_B7B_2           12.0
D_TRA4_B7A_1            6.0
D_TRA4_B7B_1           11.0
dtype: float64

In [ ]:
data20 = data20.fillna(0)
data20 = data20.astype(int)
data20 = data20.astype(object)

In [ ]:
data20

,D_TRA1_CASE,D_TRA2_CASE,D_TRA3_CASE,D_TRA4_CASE,D_TRA1_1_SPOT,D_TRA1_2_SPOT,D_TRA1_3_SPOT,D_TRA1_4_SPOT,D_TRA1_5_SPOT,D_TRA1_6_SPOT,D_TRA2_1_SPOT,D_TRA2_2_SPOT,D_TRA2_3_SPOT,D_TRA2_4_SPOT,D_TRA3_1_SPOT,D_TRA3_2_SPOT,D_TRA4_1_SPOT,D_TRA1_B7A_1,D_TRA1_B7A_2,D_TRA1_B7A_3,D_TRA1_B7B_1,D_TRA1_B7B_2,D_TRA1_B7B_3,D_TRA2_B7A_1,D_TRA2_B7A_2,D_TRA2_B7A_3,D_TRA2_B7B_1,D_TRA2_B7B_2,D_TRA2_B7B_3,D_TRA3_B7A_1,D_TRA3_B7B_1,D_TRA3_B7B_2,D_TRA4_B7A_1,D_TRA4_B7B_1
0,1,0,0,0,31380,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,39010,39010,39010,0,0,0,0,0,0,0,0,0,0,3,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,25010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,34380,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,32340,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,37020,37020,37020,0,0,0,0,0,0,0,0,0,0,6,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1,0,0,0,31090,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
7,1,0,0,0,34370,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,32040,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
9,1,0,0,0,31190,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
10,1,1,0,0,31370,0,0,0,0,0,31370,0,0,0,0,0,0,1,0,0,1,11,0,1,0,0,1,11,0,0,0,0,0,0
11,1,0,0,0,36020,36020,36020,36020,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
12,1,0,0,0,31130,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
13,1,0,0,0,21020,21020,21140,21050,0,0,0,0,0,0,0,0,0,2,0,0,5,10,0,0,0,0,0,0,0,0,0,0,0,0
14,1,0,0,0,25040,25040,0,0,0,0,0,0,0,0,0,0,0,2,0,0,10,11,0,0,0,0,0,0,0,0,0,0,0,0
15,1,1,0,0,36420,36430,36420,0,0,0,38030,38030,0,0,0,0,0,2,0,0,8,0,0,2,0,0,10,0,0,0,0,0,0,0
16,1,0,0,0,31190,0,0,0,0,0,0,0,0,0,0,0,0,7,11,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
17,1,0,0,0,21140,21010,0,0,0,0,0,0,0,0,0,0,0,6,2,0,10,11,0,0,0,0,0,0,0,0,0,0,0,0
18,1,1,0,0,34040,0,0,0,0,0,23310,0,0,0,0,0,0,5,0,0,11,0,0,6,11,0,11,6,0,0,0,0,0,0
19,1,0,0,0,31230,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
20,1,4,0,0,32060,0,0,0,0,0,31090,0,0,0,0,0,0,1,0,0,11,1,0,1,0,0,11,0,0,0,0,0,0,0
21,1,0,0,0,21090,21100,0,0,0,0,0,0,0,0,0,0,0,5,2,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0
22,1,0,0,0,36330,36020,0,0,0,0,0,0,0,0,0,0,0,7,0,0,7,0,0,0,0,0,0,0,0,0,0,0,0,0
23,1,0,0,0,31230,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
24,1,0,0,0,25010,0,0,0,0,0,0,0,0,0,0,0,0,5,2,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
25,1,0,0,0,38050,38050,0,0,0,0,0,0,0,0,0,0,0,6,5,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
26,1,0,0,0,37010,26010,0,0,0,0,0,0,0,0,0,0,0,11,10,0,1,10,11,0,0,0,0,0,0,0,0,0,0,0
27,1,0,0,0,39020,39020,39020,39010,0,0,0,0,0,0,0,0,0,3,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0
28,1,0,0,0,31060,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0
29,1,0,0,0,31200,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
30,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
31,1,0,0,0,31060,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
32,1,0,0,0,34040,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,11,6,0,0,0,0,0,0,0,0,0,0,0,0
33,1,0,0,0,39020,39020,39020,39010,0,0,0,0,0,0,0,0,0,5,3,0,6,11,0,0,0,0,0,0,0,0,0,0,0,0
34,1,0,0,0,31280,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
35,1,0,0,0,31110,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
36,1,0,0,0,31220,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
37,1,0,0,0,26030,26010,26310,0,0,0,0,0,0,0,0,0,0,2,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
38,1,0,0,0,36010,36010,0,0,0,0,0,0,0,0,0,0,0,9,0,0,9,11,0,0,0,0,0,0,0,0,0,0,0,0
39,1,0,0,0,31200,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
40,1,0,0,0,21030,21090,21090,21110,0,0,0,0,0,0,0,0,0,2,0,0,1,11,4,0,0,0,0,0,0,0,0,0,0,0
41,1,0,0,0,32400,32400,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
42,1,1,0,0,21090,0,0,0,0,0,37010,37010,0,0,0,0,0,2,0,0,10,11,0,6,0,0,10,11,0,0,0,0,0,0
43,1,0,0,0,37010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
44,1,0,0,0,38090,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,4,1,11,0,0,0,0,0,0,0,0,0,0,0
45,1,0,0,0,38080,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
46,1,0,0,0,38110,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
47,1,0,0,0,32410,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
48,1,0,0,0,37020,37020,37020,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
49,1,0,0,0,38070,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
50,1,0,0,0,26030,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
51,1,0,0,0,37020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
52,1,0,0,0,32040,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
53,1,0,0,0,38360,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
54,1,1,0,0,26040,0,0,0,0,0,26040,26020,0,0,0,0,0,6,0,0,6,0,0,6,0,0,6,0,0,0,0,0,0,0
55,1,0,0,0,37020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
56,1,0,0,0,38110,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
57,1,0,0,0,26040,37350,37420,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
58,1,0,0,0,38070,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
59,1,0,0,0,38080,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0
60,1,0,0,0,37430,37430,37430,0,0,0,0,0,0,0,0,0,0,1,4,0,4,7,0,0,0,0,0,0,0,0,0,0,0,0
61,1,0,0,0,39020,39020,39020,0,0,0,0,0,0,0,0,0,0,3,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0
62,1,0,0,0,26310,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
63,1,0,0,0,38380,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,6,11,0,0,0,0,0,0,0,0,0,0,0,0
64,1,0,0,0,38100,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
65,1,0,0,0,37020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
66,1,0,0,0,38060,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
67,1,0,0,0,21090,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,5,6,0,0,0,0,0,0,0,0,0,0,0,0
68,1,0,0,0,37070,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,6,11,0,0,0,0,0,0,0,0,0,0,0,0
69,1,0,0,0,37360,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
70,1,0,0,0,21090,0,0,0,0,0,0,0,0,0,0,0,0,6,2,0,2,5,0,0,0,0,0,0,0,0,0,0,0,0
71,1,0,0,0,37100,37100,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
72,1,0,0,0,35380,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
73,1,0,0,0,37010,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,6,11,0,0,0,0,0,0,0,0,0,0,0,0
74,1,0,0,0,26310,0,0,0,0,0,0,0,0,0,0,0,0,6,11,0,5,11,0,0,0,0,0,0,0,0,0,0,0,0
75,1,0,0,0,31100,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
76,1,0,0,0,38400,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
77,1,0,0,0,37010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
78,1,1,0,0,11010,11140,11050,0,0,0,21140,21050,21090,21090,0,0,0,2,5,0,5,11,0,2,6,0,10,11,6,0,0,0,0,0
79,1,0,0,0,11230,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
80,1,0,0,0,11010,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
81,1,1,0,0,11010,0,0,0,0,0,37010,37010,0,37010,0,0,0,2,0,0,11,0,0,1,0,0,11,0,0,0,0,0,0,0
82,1,0,0,0,21310,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
83,1,0,0,0,37070,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
84,1,0,0,0,31230,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
85,1,0,0,0,11140,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
86,1,0,0,0,11010,0,0,0,0,0,0,0,0,0,0,0,0,5,6,0,11,6,0,0,0,0,0,0,0,0,0,0,0,0
87,1,0,0,0,33380,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
88,1,0,0,0,32060,32060,32060,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
89,1,0,0,0,31370,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
90,1,0,0,0,32360,0,0,0,0,0,0,0,0,0,0,0,0,9,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0
91,1,0,0,0,31020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
92,1,0,0,0,11040,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
93,1,0,0,0,31370,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
94,1,0,0,0,34020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
95,1,0,0,0,11010,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
96,1,0,0,0,32410,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
97,1,0,0,0,39020,39020,39020,0,0,0,0,0,0,0,0,0,0,3,0,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0
98,1,0,0,0,31200,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
99,1,0,0,0,11140,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
100,1,0,0,0,31380,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
101,1,0,0,0,11160,0,0,0,0,0,0,0,0,0,0,0,0,1,4,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
102,1,0,0,0,34020,34020,34020,0,0,0,0,0,0,0,0,0,0,4,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
103,1,0,0,0,39010,0,39010,39010,39010,0,0,0,0,0,0,0,0,3,10,0,10,11,0,0,0,0,0,0,0,0,0,0,0,0
104,1,3,0,0,35380,0,0,0,0,0,36440,0,0,0,0,0,0,7,11,0,7,11,0,1,0,0,1,11,0,0,0,0,0,0
105,1,0,0,0,36310,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
106,1,0,0,0,32410,32410,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
107,1,0,0,0,36460,36460,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
108,1,0,0,0,36040,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
109,1,0,0,0,36360,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
110,1,0,0,0,11240,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0
111,1,0,0,0,36370,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
112,1,0,0,0,36330,36030,36030,0,0,0,0,0,0,0,0,0,0,1,0,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
113,1,0,0,0,36440,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
114,1,0,0,0,36450,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
115,1,1,0,0,36440,0,0,0,0,0,36370,36320,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0
116,1,0,0,0,33340,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
117,1,4,0,0,34350,0,0,0,0,0,33330,0,0,0,0,0,0,1,0,0,11,1,0,1,0,0,1,11,0,0,0,0,0,0
118,1,4,0,0,35010,35010,35010,35010,35010,0,21120,0,0,0,0,0,0,1,11,0,1,11,0,6,2,10,10,0,0,0,0,0,0,0
119,1,0,0,0,34020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
120,1,0,0,0,34020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
121,1,0,0,0,21090,21140,0,0,0,0,0,0,0,0,0,0,0,2,0,0,5,10,0,0,0,0,0,0,0,0,0,0,0,0
122,1,0,0,0,34060,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
123,1,0,0,0,33330,33330,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
124,1,0,0,0,35020,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
125,1,0,0,0,34030,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
126,1,0,0,0,34330,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
127,1,0,0,0,21310,21310,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
128,1,0,0,0,21090,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
129,1,0,0,0,38330,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
130,1,0,0,0,21310,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
131,1,0,0,0,37020,37020,0,0,0,0,0,0,0,0,0,0,0,11,1,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
132,1,0,0,0,21110,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,6,0,0,0,0,0,0,0,0,0,0,0,0
133,1,0,0,0,38100,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
134,1,0,0,0,34020,34020,0,0,0,0,0,0,0,0,0,0,0,2,1,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
135,1,0,0,0,35020,35020,35020,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
136,1,0,0,0,34380,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
137,1,0,0,0,25040,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
138,1,0,0,0,34080,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
139,1,0,0,0,34060,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
140,1,0,0,0,25040,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
141,1,0,0,0,34350,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
142,1,0,0,0,31240,0,0,0,0,0,0,0,0,0,0,0,0,11,1,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
143,1,0,0,0,24040,24040,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
144,1,0,0,0,33320,33320,33320,0,0,0,0,0,0,0,0,0,0,11,1,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
145,1,0,0,0,31370,0,0,0,0,0,0,0,0,0,0,0,0,11,1,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
146,1,0,0,0,31240,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
147,1,0,0,0,23010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
148,1,0,0,0,21090,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0
149,1,0,0,0,31150,31150,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
150,1,0,0,0,31370,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
151,1,0,0,0,32010,32010,0,0,0,0,0,0,0,0,0,0,0,2,5,0,11,6,0,0,0,0,0,0,0,0,0,0,0,0
152,1,0,0,0,32410,32410,0,32060,32060,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
153,1,1,0,0,23010,0,0,0,0,0,31350,0,0,0,0,0,0,5,0,0,11,0,0,5,0,0,11,0,0,0,0,0,0,0
154,1,0,0,0,32410,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
155,1,0,0,0,31350,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
156,1,0,0,0,31090,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
157,1,0,0,0,39020,39020,39020,0,0,0,0,0,0,0,0,0,0,3,5,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0
158,1,0,0,0,33320,0,0,0,0,0,0,0,0,0,0,0,0,5,6,0,6,11,0,0,0,0,0,0,0,0,0,0,0,0
159,1,0,0,0,39010,39020,39020,39020,39020,39010,0,0,0,0,0,0,0,6,3,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0
160,1,0,0,0,39010,39020,39020,0,0,0,0,0,0,0,0,0,0,5,3,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0
161,1,0,0,0,35010,36030,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
162,1,0,0,0,33320,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
163,1,0,0,0,39020,0,0,0,0,0,0,0,0,0,0,0,0,3,11,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
164,1,0,0,0,11100,0,0,0,0,0,0,0,0,0,0,0,0,2,11,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
165,1,0,0,0,31070,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
166,1,0,0,0,23010,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
167,1,0,0,0,11010,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,11,0,0,0,0,0,0,0,0,0,0,0,0
168,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
169,1,0,0,0,32410,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
170,1,0,0,0,31130,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
171,1,0,0,0,11240,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
172,1,0,0,0,11050,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
173,1,0,0,0,32060,32060,32060,32060,32060,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
174,1,0,0,0,32310,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
175,1,0,0,0,25040,0,0,0,0,0,0,0,0,0,0,0,0,2,5,0,10,0,0,0,0,0,0,0,0,0,0,0,0,0
176,1,0,0,0,31120,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
177,1,0,0,0,11230,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,11,0,0,0,0,0,0,0,0,0,0,0,0
178,1,0,0,0,31260,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
179,1,0,0,0,31370,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
180,1,0,0,0,31130,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
181,1,0,0,0,31270,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
182,1,0,0,0,32060,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
183,1,1,1,1,31010,0,0,0,0,0,11010,0,0,0,31120,0,11010,6,0,0,11,0,0,6,0,0,11,0,0,6,11,0,6,11
184,1,2,0,0,32370,32370,0,0,0,0,32360,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0
185,1,0,0,0,31220,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
186,1,0,0,0,21090,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,6,0,0,0,0,0,0,0,0,0,0,0,0
187,1,0,0,0,35380,35380,35380,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
188,1,0,0,0,31020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
189,1,0,0,0,21090,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
190,1,0,0,0,21050,0,0,0,0,0,0,0,0,0,0,0,0,2,10,11,10,11,0,0,0,0,0,0,0,0,0,0,0,0
191,1,0,0,0,31020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
192,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
193,1,0,0,0,31130,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
194,1,0,0,0,11190,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,11,0,0,0,0,0,0,0,0,0,0,0,0
195,1,0,0,0,23310,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
196,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
197,1,0,0,0,34370,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
198,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
199,1,0,0,0,31020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
200,1,0,0,0,31250,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
201,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,9,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0
202,1,0,0,0,31240,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
203,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
204,1,0,0,0,32350,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
205,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
206,1,0,0,0,32330,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
207,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,11,1,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
208,1,0,0,0,31370,0,0,0,0,0,0,0,0,0,0,0,0,1,11,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
209,1,0,0,0,11240,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
210,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
211,1,0,0,0,11220,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
212,1,0,0,0,11020,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
213,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,9,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
214,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
215,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,11,1,0,0,0,0,0,0,0,0,0,0,0,0
216,1,0,0,0,21310,21310,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
217,1,0,0,0,32050,32050,32410,32410,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
218,1,0,0,0,11160,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
219,1,0,0,0,11010,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
220,1,0,0,0,11160,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
221,1,0,0,0,11010,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
222,1,0,0,0,11220,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
223,1,0,0,0,11230,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
224,1,0,0,0,11220,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
225,1,0,0,0,23060,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
226,1,0,0,0,11230,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
227,1,0,0,0,11220,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
228,1,0,0,0,11230,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
229,1,0,0,0,11220,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
230,1,0,0,0,11230,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
231,1,0,0,0,11230,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
232,1,0,0,0,11010,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
233,1,0,0,0,11220,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
234,1,0,0,0,11020,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0
235,1,0,0,0,32310,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
236,1,0,0,0,32320,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
237,1,0,0,0,39020,39020,39010,39020,39020,39020,0,0,0,0,0,0,0,6,3,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0
238,1,0,0,0,31210,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
239,1,0,0,0,37040,37040,37040,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
240,1,1,0,0,31110,0,0,0,0,0,31110,0,0,0,0,0,0,5,0,0,11,0,0,5,0,0,11,0,0,0,0,0,0,0
241,1,0,0,0,11220,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0
242,1,0,0,0,32030,32030,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
243,1,0,0,0,34050,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
244,1,0,0,0,32030,32030,32030,0,0,0,0,0,0,0,0,0,0,1,0,0,1,11,0,0,0,0,0,0,0,0,0,0,0,0
245,1,0,0,0,31030,31030,0,0,0,0,0,0,0,0,0,0,0,5,6,0,5,6,0,0,0,0,0,0,0,0,0,0,0,0
246,1,0,0,0,32030,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
247,1,0,0,0,31010,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
248,1,0,0,0,32020,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
spot_max = {1: 6, 2: 4, 3: 2, 4: 1}

threshold = {1: 3, 2: 3, 3: 1, 4: 1}

result = defaultdict(lambda: {"car": 0, "non_car": 0, "total": 0})

for _, row in data20.iterrows():
    for t in range(1, 5):
        case = row[f'D_TRA{t}_CASE']
        if case != 1:
            continue
        for i in range(1, spot_max[t] + 1):
            spot_col = f'D_TRA{t}_{i}_SPOT'
            region = row.get(spot_col, 0)
            if pd.isna(region) or int(region) == 0:
                continue
            if i <= threshold[t]:
                b7_col = f'D_TRA{t}_B7A_{i}'
            else:
                b7_col = f'D_TRA{t}_B7B_{i - threshold[t]}'
            mode = row.get(b7_col, 0)
            is_car = (int(mode) == 1)
            region = int(region)
            result[region]["total"] += 1
            if is_car:
                result[region]["car"] += 1
            else:
                result[region]["non_car"] += 1

summary = pd.DataFrame([
    {
        "region_code": region,
        "car_count": v["car"],
        "non_car_count": v["non_car"],
        "total_count": v["total"],
        "car_ratio": round(v["car"] / v["total"], 3)
    }
    for region, v in result.items()
]).sort_values("region_code").reset_index(drop=True)

summary

     region_code  car_count  non_car_count  total_count  car_ratio
0          11010          0             17           17      0.000
1          11020          1              4            5      0.200
2          11030          0              4            4      0.000
3          11040          1              4            5      0.200
4          11050          0              4            4      0.000
5          11060          1              3            4      0.250
6          11070          0              2            2      0.000
7          11100          1              1            2      0.500
8          11120          0              1            1      0.000
9          11130          0              1            1      0.000
10         11140          0              6            6      0.000
11         11160          3              1            4      0.750
12         11190          0              1            1      0.000
13         11210          0              1            1      0.000
14         11220          1              7            8      0.125
15         11230          0             13           13      0.000
16         11240          2              3            5      0.400
17         21010          2              2            4      0.500
18         21020          1              3            4      0.250
19         21030          0              1            1      0.000
20         21040          0              1            1      0.000
21         21050          1              4            5      0.200
22         21070          1              0            1      1.000
23         21090          5             15           20      0.250
24         21100          0              1            1      0.000
25         21110          1              1            2      0.500
26         21120          1              0            1      1.000
27         21140          1              6            7      0.143
28         21310          6              3            9      0.667
29         22010          4              3            7      0.571
30         22020          4              1            5      0.800
31         22050          1              0            1      1.000
32         22060          1              1            2      0.500
33         22070          0              1            1      0.000
34         23010          1              2            3      0.333
35         23060          0              1            1      0.000
36         23310          1              1            2      0.500
37         24010          4              3            7      0.571
38         24030          1              1            2      0.500
39         24040          1              1            2      0.500
40         25010          1              1            2      0.500
41         25020          1              0            1      1.000
42         25030          1              1            2      0.500
43         25040          6              3            9      0.667
44         25050          1              0            1      1.000
45         26010          1              2            3      0.333
46         26020          1              2            3      0.333
47         26030          3              1            4      0.750
48         26040          1              2            3      0.333
49         26310          0              3            3      0.000
50         31010         12              6           18      0.667
51         31020          5              1            6      0.833
52         31030          0              4            4      0.000
53         31060          0              3            3      0.000
54         31070          1              0            1      1.000
55         31090          1              3            4      0.250
56         31100          1              0            1      1.000
57         31110          0              3            3      0.000
58         31120          0              2            2      0.000
59         31130          3              1            4      0.750
60         31150          1              1            2      0.500
61         31190          2              1            3      0.667
62         31200          4              2            6      0.667
63         31210          1              0            1      1.000
64         31220          2              0            2      1.000
65         31230          3              1            4      0.750
66         31240          3              1            4      0.750
67         31250          1              0            1      1.000
68         31260          1              0            1      1.000
69         31270          1              0            1      1.000
70         31280          1              0            1      1.000
71         31350          0              2            2      0.000
72         31370          8              2           10      0.800
73         31380          1              1            2      0.500
74         32010          6              5           11      0.545
75         32020          4              1            5      0.800
76         32030         10              9           19      0.526
77         32040          3              2            5      0.600
78         32050          2              1            3      0.667
79         32060          9              6           15      0.600
80         32070          1              0            1      1.000
81         32310          3              0            3      1.000
82         32320          2              0            2      1.000
83         32330          1              0            1      1.000
84         32340          2              0            2      1.000
85         32350          1              0            1      1.000
86         32360          1              1            2      0.500
87         32370          1              1            2      0.500
88         32390          1              1            2      0.500
89         32400          2              1            3      0.667
90         32410         11              4           15      0.733
91         33020          0              1            1      0.000
92         33030          2              0            2      1.000
93         33040          2              1            3      0.667
94         33320          2              3            5      0.400
95         33330          1              1            2      0.500
96         33340          0              1            1      0.000
97         33350          2              1            3      0.667
98         33360          1              2            3      0.333
99         33370          1              0            1      1.000
100        33380          1              0            1      1.000
101        33390          2              0            2      1.000
102        34010          1              0            1      1.000
103        34020          8              5           13      0.615
104        34030          2              1            3      0.667
105        34040          1              2            3      0.333
106        34050          3              0            3      1.000
107        34060          2              0            2      1.000
108        34080          3              2            5      0.600
109        34330          1              0            1      1.000
110        34350          3              0            3      1.000
111        34370          3              0            3      1.000
112        34380          2              7            9      0.222
113        35010          8              5           13      0.615
114        35020          3              2            5      0.600
115        35040          1              0            1      1.000
116        35050          6              2            8      0.750
117        35060          2              0            2      1.000
118        35310          0              1            1      0.000
119        35330          3              0            3      1.000
120        35360          1              1            2      0.500
121        35370          1              1            2      0.500
122        35380          5              7           12      0.417
123        36010          2              7            9      0.222
124        36020          4              4            8      0.500
125        36030          3              3            6      0.500
126        36040          1              0            1      1.000
127        36310          4              3            7      0.571
128        36320          0              1            1      0.000
129        36330          4              3            7      0.571
130        36350          1              0            1      1.000
131        36360          1              0            1      1.000
132        36370          2              0            2      1.000
133        36380          1              1            2      0.500
134        36390          1              1            2      0.500
135        36400          2              2            4      0.500
136        36420          2              2            4      0.500
137        36430          2              1            3      0.667
138        36440          2              0            2      1.000
139        36450          3              0            3      1.000
140        36460          1              1            2      0.500
141        36470          1              2            3      0.333
142        36480          1              0            1      1.000
143        37010          7             16           23      0.304
144        37020          5              8           13      0.385
145        37040          1              3            4      0.250
146        37050          2              1            3      0.667
147        37060          1              0            1      1.000
148        37070          1              1            2      0.500
149        37080          1              0            1      1.000
150        37090          1              0            1      1.000
151        37100          3              3            6      0.500
152        37350          3              2            5      0.600
153        37360          2              0            2      1.000
154        37410          1              0            1      1.000
155        37420          0              1            1      0.000
156        37430          1              2            3      0.333
157        38030          0              4            4      0.000
158        38050          4              4            8      0.500
159        38060          2              2            4      0.500
160        38070          1              1            2      0.500
161        38080          1              2            3      0.333
162        38090          1              0            1      1.000
163        38100          4              1            5      0.800
164        38110          3              1            4      0.750
165        38330          1              0            1      1.000
166        38350          2              0            2      1.000
167        38360          2              1            3      0.667
168        38370          1              1            2      0.500
169        38380          0              1            1      0.000
170        38390          1              0            1      1.000
171        38400          3              0            3      1.000
172        39010          5             25           30      0.167
173        39020          4             33           37      0.108

In [ ]:
summary.sort_values(by='car_ratio', ascending=False)

     region_code  car_count  non_car_count  total_count  car_ratio
22         21070          1              0            1      1.000
44         25050          1              0            1      1.000
31         22050          1              0            1      1.000
41         25020          1              0            1      1.000
26         21120          1              0            1      1.000
166        38350          2              0            2      1.000
165        38330          1              0            1      1.000
162        38090          1              0            1      1.000
139        36450          3              0            3      1.000
153        37360          2              0            2      1.000
150        37090          1              0            1      1.000
149        37080          1              0            1      1.000
147        37060          1              0            1      1.000
142        36480          1              0            1      1.000
110        34350          3              0            3      1.000
111        34370          3              0            3      1.000
117        35060          2              0            2      1.000
115        35040          1              0            1      1.000
119        35330          3              0            3      1.000
131        36360          1              0            1      1.000
132        36370          2              0            2      1.000
126        36040          1              0            1      1.000
130        36350          1              0            1      1.000
138        36440          2              0            2      1.000
102        34010          1              0            1      1.000
109        34330          1              0            1      1.000
101        33390          2              0            2      1.000
99         33370          1              0            1      1.000
107        34060          2              0            2      1.000
106        34050          3              0            3      1.000
81         32310          3              0            3      1.000
80         32070          1              0            1      1.000
83         32330          1              0            1      1.000
82         32320          2              0            2      1.000
84         32340          2              0            2      1.000
85         32350          1              0            1      1.000
92         33030          2              0            2      1.000
100        33380          1              0            1      1.000
63         31210          1              0            1      1.000
64         31220          2              0            2      1.000
68         31260          1              0            1      1.000
67         31250          1              0            1      1.000
69         31270          1              0            1      1.000
70         31280          1              0            1      1.000
54         31070          1              0            1      1.000
56         31100          1              0            1      1.000
171        38400          3              0            3      1.000
154        37410          1              0            1      1.000
170        38390          1              0            1      1.000
51         31020          5              1            6      0.833
30         22020          4              1            5      0.800
163        38100          4              1            5      0.800
75         32020          4              1            5      0.800
72         31370          8              2           10      0.800
164        38110          3              1            4      0.750
65         31230          3              1            4      0.750
59         31130          3              1            4      0.750
47         26030          3              1            4      0.750
66         31240          3              1            4      0.750
116        35050          6              2            8      0.750
11         11160          3              1            4      0.750
90         32410         11              4           15      0.733
167        38360          2              1            3      0.667
146        37050          2              1            3      0.667
78         32050          2              1            3      0.667
97         33350          2              1            3      0.667
50         31010         12              6           18      0.667
43         25040          6              3            9      0.667
28         21310          6              3            9      0.667
137        36430          2              1            3      0.667
104        34030          2              1            3      0.667
93         33040          2              1            3      0.667
62         31200          4              2            6      0.667
61         31190          2              1            3      0.667
89         32400          2              1            3      0.667
113        35010          8              5           13      0.615
103        34020          8              5           13      0.615
79         32060          9              6           15      0.600
114        35020          3              2            5      0.600
152        37350          3              2            5      0.600
77         32040          3              2            5      0.600
108        34080          3              2            5      0.600
37         24010          4              3            7      0.571
127        36310          4              3            7      0.571
129        36330          4              3            7      0.571
29         22010          4              3            7      0.571
74         32010          6              5           11      0.545
76         32030         10              9           19      0.526
32         22060          1              1            2      0.500
36         23310          1              1            2      0.500
7          11100          1              1            2      0.500
168        38370          1              1            2      0.500
160        38070          1              1            2      0.500
158        38050          4              4            8      0.500
88         32390          1              1            2      0.500
60         31150          1              1            2      0.500
73         31380          1              1            2      0.500
87         32370          1              1            2      0.500
148        37070          1              1            2      0.500
151        37100          3              3            6      0.500
135        36400          2              2            4      0.500
159        38060          2              2            4      0.500
124        36020          4              4            8      0.500
120        35360          1              1            2      0.500
25         21110          1              1            2      0.500
17         21010          2              2            4      0.500
40         25010          1              1            2      0.500
39         24040          1              1            2      0.500
38         24030          1              1            2      0.500
42         25030          1              1            2      0.500
133        36380          1              1            2      0.500
140        36460          1              1            2      0.500
121        35370          1              1            2      0.500
125        36030          3              3            6      0.500
134        36390          1              1            2      0.500
136        36420          2              2            4      0.500
86         32360          1              1            2      0.500
95         33330          1              1            2      0.500
122        35380          5              7           12      0.417
16         11240          2              3            5      0.400
94         33320          2              3            5      0.400
144        37020          5              8           13      0.385
46         26020          1              2            3      0.333
141        36470          1              2            3      0.333
161        38080          1              2            3      0.333
156        37430          1              2            3      0.333
34         23010          1              2            3      0.333
48         26040          1              2            3      0.333
98         33360          1              2            3      0.333
105        34040          1              2            3      0.333
45         26010          1              2            3      0.333
143        37010          7             16           23      0.304
18         21020          1              3            4      0.250
23         21090          5             15           20      0.250
5          11060          1              3            4      0.250
55         31090          1              3            4      0.250
145        37040          1              3            4      0.250
112        34380          2              7            9      0.222
123        36010          2              7            9      0.222
21         21050          1              4            5      0.200
3          11040          1              4            5      0.200
1          11020          1              4            5      0.200
172        39010          5             25           30      0.167
27         21140          1              6            7      0.143
14         11220          1              7            8      0.125
173        39020          4             33           37      0.108
20         21040          0              1            1      0.000
19         21030          0              1            1      0.000
12         11190          0              1            1      0.000
24         21100          0              1            1      0.000
4          11050          0              4            4      0.000
2          11030          0              4            4      0.000
8          11120          0              1            1      0.000
6          11070          0              2            2      0.000
9          11130          0              1            1      0.000
10         11140          0              6            6      0.000
13         11210          0              1            1      0.000
0          11010          0             17           17      0.000
33         22070          0              1            1      0.000
35         23060          0              1            1      0.000
15         11230          0             13           13      0.000
53         31060          0              3            3      0.000
49         26310          0              3            3      0.000
57         31110          0              3            3      0.000
52         31030          0              4            4      0.000
71         31350          0              2            2      0.000
96         33340          0              1            1      0.000
91         33020          0              1            1      0.000
58         31120          0              2            2      0.000
118        35310          0              1            1      0.000
128        36320          0              1            1      0.000
155        37420          0              1            1      0.000
157        38030          0              4            4      0.000
169        38380          0              1            1      0.000

## 2022 데이터 차량 의존도 체크

In [ ]:
url_2022 = file_path = '/content/drive/MyDrive/공모전/공모전/BDA/data/2022년_국민여행조사_원자료_국내여행/2022년_1인필터링_관광.csv'

In [ ]:
df_2022 = pd.read_csv(url_2022)

In [ ]:
list_col13 = ['D_TRA1_CASE','D_TRA2_CASE',
'D_TRA3_CASE','D_TRA4_CASE',
'D_TRA1_1_SPOT',
'D_TRA1_2_SPOT',
'D_TRA1_3_SPOT',
'D_TRA1_4_SPOT',
'D_TRA1_5_SPOT',
'D_TRA1_6_SPOT',
'D_TRA1_7_SPOT',
'D_TRA1_8_SPOT',
'D_TRA1_9_SPOT',
'D_TRA2_1_SPOT',
'D_TRA2_2_SPOT',
'D_TRA2_3_SPOT',
'D_TRA3_1_SPOT',
'D_TRA3_2_SPOT',
'D_TRA3_3_SPOT',
'D_TRA4_1_SPOT',
'A1_1']

data_2022 = df_2022[list_col13]

In [ ]:
data_2022_clean = data_2022.replace(' ', 0).fillna(0)
data_2022_clean = data_2022_clean.astype(int)

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

print(data_2022_clean.sum())

D_TRA1_CASE           455
D_TRA2_CASE            69
D_TRA3_CASE             3
D_TRA4_CASE             1
D_TRA1_1_SPOT    12517560
D_TRA1_2_SPOT     3362540
D_TRA1_3_SPOT     1452720
D_TRA1_4_SPOT      787450
D_TRA1_5_SPOT      511760
D_TRA1_6_SPOT      281800
D_TRA1_7_SPOT      188110
D_TRA1_8_SPOT      188110
D_TRA1_9_SPOT       78020
D_TRA2_1_SPOT     1332320
D_TRA2_2_SPOT      325850
D_TRA2_3_SPOT       36310
D_TRA3_1_SPOT      104060
D_TRA3_2_SPOT       39020
D_TRA3_3_SPOT       39020
D_TRA4_1_SPOT       31010
A1_1                 1046
dtype: int64

In [ ]:
list_col13_2 = ['D_TRA1_CASE','D_TRA2_CASE',
'D_TRA3_CASE','D_TRA4_CASE',
'D_TRA1_1_SPOT',
'D_TRA1_2_SPOT',
'D_TRA1_3_SPOT',
'D_TRA1_4_SPOT',
'D_TRA1_5_SPOT',
'D_TRA1_6_SPOT',
'D_TRA1_7_SPOT',
'D_TRA1_8_SPOT',
'D_TRA1_9_SPOT',
'D_TRA2_1_SPOT',
'D_TRA2_2_SPOT',
'D_TRA2_3_SPOT',
'D_TRA3_1_SPOT',
'D_TRA3_2_SPOT',
'D_TRA3_3_SPOT',
'D_TRA4_1_SPOT',
'A1_1']

data_2022 = df_2022[list_col13_2]

In [ ]:
from collections import defaultdict

df_2022_all_2 = data_2022[
    (data_2022['D_TRA1_CASE'] == 1) &
    (data_2022['D_TRA2_CASE'] == 1) &
    (data_2022['D_TRA3_CASE'] == 1)
].copy()

df_2022_not_all_2 = data_2022.drop(df_2022_all_2.index).copy()

mask_not_all2_specific = (
    df_2022['D_TRA1_CASE'].isin([2, 3, 4, 5]) |
    df_2022['D_TRA2_CASE'].isin([2, 3, 4, 5]) |
    df_2022['D_TRA3_CASE'].isin([2, 3, 4, 5])
)

df_2022_not_all_2_rest = df_2022_not_all_2[
    ~mask_not_all2_specific.loc[df_2022_not_all_2.index]
].copy()

df_2022_combined = pd.concat([df_2022_all_2, df_2022_not_all_2_rest], axis=0)
df_2022_combined.reset_index(drop=True, inplace=True)

spot_cols = list_col13[4:-1]

result = defaultdict(lambda: {"car": 0, "non_car": 0, "total": 0})

for _, row in df_2022_combined.iterrows():
    is_car = (row['A1_1'] == 1)
    for col in spot_cols:
        region = row[col]
        if pd.isna(region) or region == 0:
            continue

        try:
            region = int(str(region).strip())
        except ValueError:
            continue
        result[region]["total"] += 1
        if is_car:
            result[region]["car"] += 1
        else:
            result[region]["non_car"] += 1


region_df_2022 = pd.DataFrame([
    {
        "region_code": region,
        "car_count": counts["car"],
        "non_car_count": counts["non_car"],
        "total_count": counts["total"],
        "car_ratio": round(counts["car"] / counts["total"], 3)
    }
    for region, counts in result.items()
    if counts["total"] > 0
]).sort_values("region_code").reset_index(drop=True)

In [ ]:
print(region_df_2022.sort_values(by='car_ratio', ascending=False))

     region_code  car_count  non_car_count  total_count  car_ratio
8          11120          1              0            1      1.000
24         21060          3              0            3      1.000
30         21150          1              0            1      1.000
28         21120          1              0            1      1.000
73         31370          3              0            3      1.000
78         32050          2              0            2      1.000
92         33340          1              0            1      1.000
95         33390          1              0            1      1.000
88         33020          4              0            4      1.000
94         33380         12              0           12      1.000
87         32400          3              0            3      1.000
84         32350          1              0            1      1.000
83         32340          1              0            1      1.000
82         32330          4              0            4      1.000
81         32320          1              0            1      1.000
80         32310          1              0            1      1.000
93         33370          1              0            1      1.000
49         25030          1              0            1      1.000
52         26010          2              0            2      1.000
51         25050          1              0            1      1.000
44         24030          1              0            1      1.000
45         24040          1              0            1      1.000
47         25010          1              0            1      1.000
46         24050          1              0            1      1.000
43         24020          2              0            2      1.000
42         24010          4              0            4      1.000
37         23040          3              0            3      1.000
38         23050          3              0            3      1.000
36         23010          6              0            6      1.000
35         22070          1              0            1      1.000
34         22060          1              0            1      1.000
33         22020          2              0            2      1.000
153        38340          2              0            2      1.000
154        38350          2              0            2      1.000
152        38330          1              0            1      1.000
155        38360          3              0            3      1.000
156        38370          1              0            1      1.000
149        38090          6              0            6      1.000
148        38080          2              0            2      1.000
146        38060          2              0            2      1.000
142        37390          1              0            1      1.000
141        37360          3              0            3      1.000
140        37350          4              0            4      1.000
119        36040          2              0            2      1.000
120        36060          3              0            3      1.000
121        36310         10              0           10      1.000
122        36320          1              0            1      1.000
125        36370          1              0            1      1.000
112        35060          1              0            1      1.000
114        35370          5              0            5      1.000
115        35380          6              0            6      1.000
116        36010          2              0            2      1.000
107        34370          2              0            2      1.000
111        35050          1              0            1      1.000
110        35030          2              0            2      1.000
108        34380          5              0            5      1.000
104        34330          2              0            2      1.000
105        34340          1              0            1      1.000
106        34360          1              0            1      1.000
102        34080          5              0            5      1.000
72         31280          2              0            2      1.000
69         31250          1              0            1      1.000
68         31240          4              0            4      1.000
66         31220          2              0            2      1.000
128        36450          1              0            1      1.000
129        36460          3              0            3      1.000
131        37010          8              0            8      1.000
133        37030          1              0            1      1.000
134        37040          2              0            2      1.000
139        37330          3              0            3      1.000
138        37100          1              0            1      1.000
136        37060          1              0            1      1.000
101        34070          1              0            1      1.000
99         34040          3              0            3      1.000
98         34030          2              0            2      1.000
97         34020          9              0            9      1.000
118        36030          7              1            8      0.875
132        37020          9              2           11      0.818
77         32040          9              2           11      0.818
145        38050          4              1            5      0.800
65         31200          4              1            5      0.800
100        34060          4              1            5      0.800
61         31090          3              1            4      0.750
29         21140          3              1            4      0.750
75         32020          6              2            8      0.750
41         23310          3              1            4      0.750
103        34310          3              1            4      0.750
124        36360          3              1            4      0.750
56         31010          5              2            7      0.714
74         32010          7              3           10      0.700
79         32060         17              8           25      0.680
76         32030         29             14           43      0.674
135        37050          2              1            3      0.667
20         21010          2              1            3      0.667
22         21040          2              1            3      0.667
40         23080          2              1            3      0.667
64         31190          4              2            6      0.667
70         31260          2              1            3      0.667
109        35010          6              3            9      0.667
57         31030          4              2            6      0.667
143        37420          2              1            3      0.667
117        36020         19             13           32      0.594
23         21050          4              3            7      0.571
48         25020          1              1            2      0.500
63         31150          1              1            2      0.500
62         31120          1              1            2      0.500
150        38100          1              1            2      0.500
127        36420          1              1            2      0.500
96         34010          1              1            2      0.500
130        36480          1              1            2      0.500
123        36350          1              1            2      0.500
53         26020          1              1            2      0.500
90         33040          1              1            2      0.500
91         33320          2              2            4      0.500
21         21020          1              1            2      0.500
14         11190          2              2            4      0.500
2          11030          1              1            2      0.500
5          11090          1              1            2      0.500
3          11040          1              1            2      0.500
16         11210          1              1            2      0.500
71         31270          2              2            4      0.500
25         21090          8              9           17      0.471
1          11020          4              5            9      0.444
32         22010          3              4            7      0.429
50         25040          3              4            7      0.429
18         11230          5             10           15      0.333
7          11110          1              2            3      0.333
31         21310          2              4            6      0.333
144        38030          1              2            3      0.333
151        38110          2              4            6      0.333
54         26310          1              2            3      0.333
137        37070          1              2            3      0.333
27         21110          1              2            3      0.333
86         32390          1              2            3      0.333
113        35310          1              3            4      0.250
59         31070          1              3            4      0.250
10         11140          1              5            6      0.167
158        39010          7             40           47      0.149
159        39020          5             30           35      0.143
0          11010          1              9           10      0.100
6          11100          0              1            1      0.000
4          11050          0              2            2      0.000
13         11180          0              1            1      0.000
15         11200          0              2            2      0.000
26         21100          0              1            1      0.000
17         11220          0              2            2      0.000
19         11250          0              1            1      0.000
9          11130          0              1            1      0.000
11         11150          0              1            1      0.000
12         11170          0              1            1      0.000
58         31040          0              1            1      0.000
55         29010          0              2            2      0.000
89         33030          0              2            2      0.000
85         32360          0              4            4      0.000
67         31230          0              2            2      0.000
60         31080          0              1            1      0.000
39         23060          0              1            1      0.000
126        36390          0              2            2      0.000
147        38070          0              4            4      0.000
157        38390          0              1            1      0.000

## 2023 데이터 차량 의존도 체크

In [ ]:
url_2023 = file_path = '/content/drive/MyDrive/공모전/공모전/BDA/data/2023년_국민여행조사_원자료_국내여행/travel_alone_2023_diff.csv'

In [ ]:
df_2023 = pd.read_csv(url_2023)

/tmp/ipython-input-75-617442092.py:1: DtypeWarning: Columns (345,511,843,1343) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv(url_2023)

In [ ]:
list_col14 = ['D_TRA1_CASE','D_TRA2_CASE','D_TRA3_CASE',
'D_TRA4_CASE','D_TRA5_CASE','D_TRA6_CASE',
'D_TRA1_1_SPOT',
'D_TRA1_2_SPOT',
'D_TRA1_3_SPOT',
'D_TRA1_4_SPOT',
'D_TRA1_5_SPOT',
'D_TRA1_6_SPOT',
'D_TRA1_7_SPOT',
'D_TRA1_8_SPOT',
'D_TRA1_9_SPOT',
'D_TRA1_10_SPOT',
'D_TRA1_11_SPOT',
'D_TRA1_12_SPOT',
'D_TRA1_13_SPOT',
'D_TRA1_14_SPOT',
'D_TRA1_15_SPOT',
'D_TRA1_16_SPOT',
'D_TRA1_17_SPOT',
'D_TRA2_1_SPOT',
'D_TRA2_2_SPOT',
'D_TRA2_3_SPOT',
'D_TRA2_4_SPOT',
'D_TRA2_5_SPOT',
'D_TRA2_6_SPOT',
'D_TRA2_7_SPOT',
'D_TRA2_8_SPOT',
'D_TRA2_9_SPOT',
'D_TRA2_10_SPOT',
'D_TRA2_11_SPOT',
'D_TRA2_12_SPOT',
'D_TRA2_13_SPOT',
'D_TRA2_14_SPOT',
'D_TRA2_15_SPOT',
'D_TRA2_16_SPOT',
'D_TRA2_17_SPOT',
'D_TRA3_1_SPOT',
'D_TRA3_2_SPOT',
'D_TRA3_3_SPOT',
'D_TRA3_4_SPOT',
'D_TRA3_5_SPOT',
'D_TRA3_6_SPOT',
'D_TRA3_7_SPOT',
'D_TRA3_8_SPOT',
'D_TRA3_9_SPOT',
'D_TRA3_10_SPOT',
'D_TRA3_11_SPOT',
'D_TRA3_12_SPOT',
'D_TRA3_13_SPOT',
'D_TRA3_14_SPOT',
'D_TRA3_15_SPOT',
'D_TRA3_16_SPOT',
'D_TRA3_17_SPOT',
'D_TRA4_1_SPOT',
'D_TRA4_2_SPOT',
'D_TRA4_3_SPOT',
'D_TRA4_4_SPOT',
'D_TRA4_5_SPOT',
'D_TRA4_6_SPOT',
'D_TRA4_7_SPOT',
'D_TRA4_8_SPOT',
'D_TRA4_9_SPOT',
'D_TRA4_10_SPOT',
'D_TRA4_11_SPOT',
'D_TRA4_12_SPOT',
'D_TRA4_13_SPOT',
'D_TRA4_14_SPOT',
'D_TRA4_15_SPOT',
'D_TRA4_16_SPOT',
'D_TRA4_17_SPOT',
'D_TRA5_1_SPOT',
'D_TRA5_2_SPOT',
'D_TRA5_3_SPOT',
'D_TRA5_4_SPOT',
'D_TRA5_5_SPOT',
'D_TRA5_6_SPOT',
'D_TRA5_7_SPOT',
'D_TRA5_8_SPOT',
'D_TRA5_9_SPOT',
'D_TRA5_10_SPOT',
'D_TRA5_11_SPOT',
'D_TRA5_12_SPOT',
'D_TRA5_13_SPOT',
'D_TRA5_14_SPOT',
'D_TRA5_15_SPOT',
'D_TRA5_16_SPOT',
'D_TRA5_17_SPOT',
'D_TRA6_1_SPOT',
'D_TRA6_2_SPOT',
'D_TRA6_3_SPOT',
'D_TRA6_4_SPOT',
'D_TRA6_5_SPOT',
'D_TRA6_6_SPOT',
'D_TRA6_7_SPOT',
'D_TRA6_8_SPOT',
'D_TRA6_9_SPOT',
'D_TRA6_10_SPOT',
'D_TRA6_11_SPOT',
'D_TRA6_12_SPOT',
'D_TRA6_13_SPOT',
'D_TRA6_14_SPOT',
'D_TRA6_15_SPOT',
'D_TRA6_16_SPOT',
'D_TRA6_17_SPOT',
'A1_1']

data_2023 = df_2023[list_col14]

In [ ]:
data_2023_clean = data_2023.replace(' ', 0).fillna(0)
data_2023_clean = data_2023_clean.astype(int)

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

print(data_2023_clean.sum())

D_TRA1_CASE            5210
D_TRA2_CASE             976
D_TRA3_CASE              91
D_TRA4_CASE              34
D_TRA5_CASE              12
D_TRA6_CASE               7
D_TRA1_1_SPOT     156283260
D_TRA1_2_SPOT      57967940
D_TRA1_3_SPOT      33500180
D_TRA1_4_SPOT      20187520
D_TRA1_5_SPOT      12340990
D_TRA1_6_SPOT       8908550
D_TRA1_7_SPOT       6330360
D_TRA1_8_SPOT       4633700
D_TRA1_9_SPOT       2912300
D_TRA1_10_SPOT      1608160
D_TRA1_11_SPOT       684520
D_TRA1_12_SPOT       333400
D_TRA1_13_SPOT        78020
D_TRA1_14_SPOT        39020
D_TRA1_15_SPOT            0
D_TRA1_16_SPOT            0
D_TRA1_17_SPOT            0
D_TRA2_1_SPOT      15685780
D_TRA2_2_SPOT       3481370
D_TRA2_3_SPOT       1586830
D_TRA2_4_SPOT        787670
D_TRA2_5_SPOT        506200
D_TRA2_6_SPOT        214170
D_TRA2_7_SPOT        143090
D_TRA2_8_SPOT         71050
D_TRA2_9_SPOT         71040
D_TRA2_10_SPOT        39010
D_TRA2_11_SPOT            0
D_TRA2_12_SPOT            0
D_TRA2_13_SPOT            0
D_TRA2_14_SPOT            0
D_TRA2_15_SPOT            0
D_TRA2_16_SPOT            0
D_TRA2_17_SPOT            0
D_TRA3_1_SPOT       1413260
D_TRA3_2_SPOT        299150
D_TRA3_3_SPOT         69500
D_TRA3_4_SPOT         37430
D_TRA3_5_SPOT         37430
D_TRA3_6_SPOT         37430
D_TRA3_7_SPOT             0
D_TRA3_8_SPOT             0
D_TRA3_9_SPOT             0
D_TRA3_10_SPOT            0
D_TRA3_11_SPOT            0
D_TRA3_12_SPOT            0
D_TRA3_13_SPOT            0
D_TRA3_14_SPOT            0
D_TRA3_15_SPOT            0
D_TRA3_16_SPOT            0
D_TRA3_17_SPOT            0
D_TRA4_1_SPOT        480440
D_TRA4_2_SPOT        125450
D_TRA4_3_SPOT         66100
D_TRA4_4_SPOT         32060
D_TRA4_5_SPOT         32060
D_TRA4_6_SPOT         32060
D_TRA4_7_SPOT         32410
D_TRA4_8_SPOT         32410
D_TRA4_9_SPOT             0
D_TRA4_10_SPOT            0
D_TRA4_11_SPOT            0
D_TRA4_12_SPOT            0
D_TRA4_13_SPOT            0
D_TRA4_14_SPOT            0
D_TRA4_15_SPOT            0
D_TRA4_16_SPOT            0
D_TRA4_17_SPOT            0
D_TRA5_1_SPOT         79110
D_TRA5_2_SPOT             0
D_TRA5_3_SPOT             0
D_TRA5_4_SPOT             0
D_TRA5_5_SPOT             0
D_TRA5_6_SPOT             0
D_TRA5_7_SPOT             0
D_TRA5_8_SPOT             0
D_TRA5_9_SPOT             0
D_TRA5_10_SPOT            0
D_TRA5_11_SPOT            0
D_TRA5_12_SPOT            0
D_TRA5_13_SPOT            0
D_TRA5_14_SPOT            0
D_TRA5_15_SPOT            0
D_TRA5_16_SPOT            0
D_TRA5_17_SPOT            0
D_TRA6_1_SPOT         45100
D_TRA6_2_SPOT             0
D_TRA6_3_SPOT             0
D_TRA6_4_SPOT             0
D_TRA6_5_SPOT             0
D_TRA6_6_SPOT             0
D_TRA6_7_SPOT             0
D_TRA6_8_SPOT             0
D_TRA6_9_SPOT             0
D_TRA6_10_SPOT            0
D_TRA6_11_SPOT            0
D_TRA6_12_SPOT            0
D_TRA6_13_SPOT            0
D_TRA6_14_SPOT            0
D_TRA6_15_SPOT            0
D_TRA6_16_SPOT            0
D_TRA6_17_SPOT            0
A1_1                  10637
dtype: int64

In [ ]:
list_col14_2 = ['D_TRA1_CASE','D_TRA2_CASE','D_TRA3_CASE',
'D_TRA4_CASE','D_TRA5_CASE','D_TRA6_CASE',
'D_TRA1_1_SPOT',
'D_TRA1_2_SPOT',
'D_TRA1_3_SPOT',
'D_TRA1_4_SPOT',
'D_TRA1_5_SPOT',
'D_TRA1_6_SPOT',
'D_TRA1_7_SPOT',
'D_TRA1_8_SPOT',
'D_TRA1_9_SPOT',
'D_TRA1_10_SPOT',
'D_TRA1_11_SPOT',
'D_TRA1_12_SPOT',
'D_TRA1_13_SPOT',
'D_TRA1_14_SPOT',
'D_TRA2_1_SPOT',
'D_TRA2_2_SPOT',
'D_TRA2_3_SPOT',
'D_TRA2_4_SPOT',
'D_TRA2_5_SPOT',
'D_TRA2_6_SPOT',
'D_TRA2_7_SPOT',
'D_TRA2_8_SPOT',
'D_TRA2_9_SPOT',
'D_TRA2_10_SPOT',
'D_TRA3_1_SPOT',
'D_TRA3_2_SPOT',
'D_TRA3_3_SPOT',
'D_TRA3_4_SPOT',
'D_TRA3_5_SPOT',
'D_TRA3_6_SPOT',
'D_TRA4_1_SPOT',
'D_TRA4_2_SPOT',
'D_TRA4_3_SPOT',
'D_TRA4_4_SPOT',
'D_TRA4_5_SPOT',
'D_TRA4_6_SPOT',
'D_TRA4_7_SPOT',
'D_TRA4_8_SPOT',
'D_TRA5_1_SPOT',
'D_TRA6_1_SPOT',
'A1_1']

In [ ]:
data_2023 = df_2023[list_col14_2]

In [ ]:
data_2023 = data_2023.fillna(0)
data_2023 = data_2023.astype(int)
data_2023 = data_2023.astype(object)

In [ ]:
data_2023.sum()

D_TRA1_CASE            5210
D_TRA2_CASE             976
D_TRA3_CASE              91
D_TRA4_CASE              34
D_TRA5_CASE              12
D_TRA6_CASE               7
D_TRA1_1_SPOT     156283260
D_TRA1_2_SPOT      57967940
D_TRA1_3_SPOT      33500180
D_TRA1_4_SPOT      20187520
D_TRA1_5_SPOT      12340990
D_TRA1_6_SPOT       8908550
D_TRA1_7_SPOT       6330360
D_TRA1_8_SPOT       4633700
D_TRA1_9_SPOT       2912300
D_TRA1_10_SPOT      1608160
D_TRA1_11_SPOT       684520
D_TRA1_12_SPOT       333400
D_TRA1_13_SPOT        78020
D_TRA1_14_SPOT        39020
D_TRA2_1_SPOT      15685780
D_TRA2_2_SPOT       3481370
D_TRA2_3_SPOT       1586830
D_TRA2_4_SPOT        787670
D_TRA2_5_SPOT        506200
D_TRA2_6_SPOT        214170
D_TRA2_7_SPOT        143090
D_TRA2_8_SPOT         71050
D_TRA2_9_SPOT         71040
D_TRA2_10_SPOT        39010
D_TRA3_1_SPOT       1413260
D_TRA3_2_SPOT        299150
D_TRA3_3_SPOT         69500
D_TRA3_4_SPOT         37430
D_TRA3_5_SPOT         37430
D_TRA3_6_SPOT         37430
D_TRA4_1_SPOT        480440
D_TRA4_2_SPOT        125450
D_TRA4_3_SPOT         66100
D_TRA4_4_SPOT         32060
D_TRA4_5_SPOT         32060
D_TRA4_6_SPOT         32060
D_TRA4_7_SPOT         32410
D_TRA4_8_SPOT         32410
D_TRA5_1_SPOT         79110
D_TRA6_1_SPOT         45100
A1_1                  10637
dtype: object

In [ ]:
import pandas as pd
from collections import defaultdict

spot_max = {1: 14, 2: 10, 3: 6, 4: 8, 5:1, 6:1}

result3 = defaultdict(lambda: {"car": 0, "non_car": 0, "total": 0})

for _, row in data_2023.iterrows():
    is_car = (row['A1_1'] == 1)
    for t, max_spots in spot_max.items():
        case_val = row.get(f'D_TRA{t}_CASE', 0)
        if case_val != 1:
            continue
        for i in range(1, max_spots + 1):
            col = f'D_TRA{t}_{i}_SPOT'
            if col not in data_2023.columns:
                continue
            region = row[col]
            if pd.isna(region) or int(region) == 0:
                continue
            region = int(region)
            result[region]["total"] += 1
            if is_car:
                result[region]["car"] += 1
            else:
                result[region]["non_car"] += 1

region_df_2023 = pd.DataFrame([
    {
        "region_code": region,
        "car_count": v["car"],
        "non_car_count": v["non_car"],
        "total_count": v["total"],
        "car_ratio": round(v["car"] / v["total"], 3)
    }
    for region, v in result.items() if v["total"] > 0
]).sort_values("region_code").reset_index(drop=True)

region_df_2023

     region_code  car_count  non_car_count  total_count  car_ratio
0          11010         17             57           74      0.230
1          11020         14             30           44      0.318
2          11030         10             15           25      0.400
3          11040          3              8           11      0.273
4          11050          2             12           14      0.143
5          11060          5              1            6      0.833
6          11070          0              1            1      0.000
7          11090          2              3            5      0.400
8          11100          3              8           11      0.273
9          11110          3              4            7      0.429
10         11120          3              4            7      0.429
11         11130          0              3            3      0.000
12         11140          4             31           35      0.114
13         11150          0              1            1      0.000
14         11160          2              6            8      0.250
15         11170          0              4            4      0.000
16         11180          2              1            3      0.667
17         11190          4             22           26      0.154
18         11200          0              3            3      0.000
19         11210          6              6           12      0.500
20         11220          3              8           11      0.273
21         11230         18             38           56      0.321
22         11240          9             36           45      0.200
23         11250          0              2            2      0.000
24         21010         34             19           53      0.642
25         21020         22             21           43      0.512
26         21030          4              5            9      0.444
27         21040         26             15           41      0.634
28         21050         11              7           18      0.611
29         21060          5              2            7      0.714
30         21070          8              6           14      0.571
31         21080          0              2            2      0.000
32         21090        134             70          204      0.657
33         21100          5              6           11      0.455
34         21110          1              3            4      0.250
35         21120          1              0            1      1.000
36         21130          0              1            1      0.000
37         21140         34             24           58      0.586
38         21150          2              1            3      0.667
39         21310         37             14           51      0.725
40         22010         44             22           66      0.667
41         22020         23              8           31      0.742
42         22040          3              2            5      0.600
43         22050          3              1            4      0.750
44         22060         17              0           17      1.000
45         22070         11              4           15      0.733
46         22310          7              0            7      1.000
47         23010         39             10           49      0.796
48         23030          0              1            1      0.000
49         23040         13              2           15      0.867
50         23050         13              0           13      1.000
51         23060          3              3            6      0.500
52         23080          5              3            8      0.625
53         23310         75              4           79      0.949
54         23320          4              0            4      1.000
55         24010         49              3           52      0.942
56         24020         10              2           12      0.833
57         24030          4              0            4      1.000
58         24040         10              2           12      0.833
59         24050          2              1            3      0.667
60         25010         11              3           14      0.786
61         25020         12              9           21      0.571
62         25030         15              5           20      0.750
63         25040         32              8           40      0.800
64         25050          9              2           11      0.818
65         26010         13              1           14      0.929
66         26020         12              4           16      0.750
67         26030         11              3           14      0.786
68         26040          2              0            2      1.000
69         26310         24              5           29      0.828
70         29010         16             17           33      0.485
71         31010         43             28           71      0.606
72         31020         12              9           21      0.571
73         31030          5             10           15      0.333
74         31040          1              6            7      0.143
75         31050          2              6            8      0.250
76         31060          0              1            1      0.000
77         31070          8              4           12      0.667
78         31080          6              2            8      0.750
79         31090         14              3           17      0.824
80         31100         24             11           35      0.686
81         31110          7              6           13      0.538
82         31120          2              2            4      0.500
83         31130         16              3           19      0.842
84         31140          2              3            5      0.400
85         31150          9              5           14      0.643
86         31160          2              0            2      1.000
87         31170         10              0           10      1.000
88         31180         10              1           11      0.909
89         31190         30             14           44      0.682
90         31200         58              7           65      0.892
91         31210         13              2           15      0.867
92         31220         15              1           16      0.938
93         31230         20              3           23      0.870
94         31240         68              9           77      0.883
95         31250         25              6           31      0.806
96         31260         16              3           19      0.842
97         31270         70              6           76      0.921
98         31280         22              4           26      0.846
99         31350         17              1           18      0.944
100        31370        171             20          191      0.895
101        31380         93              6           99      0.939
102        32010         85             19          104      0.817
103        32020         51             15           66      0.773
104        32030        272             78          350      0.777
105        32040         55              7           62      0.887
106        32050         18              2           20      0.900
107        32060        221             29          250      0.884
108        32070         57             12           69      0.826
109        32310         36              5           41      0.878
110        32320          7              2            9      0.778
111        32330         20              3           23      0.870
112        32340         30              7           37      0.811
113        32350         27              6           33      0.818
114        32360         15             17           32      0.469
115        32370          2              0            2      1.000
116        32380          3              0            3      1.000
117        32390         17              6           23      0.739
118        32400         25              0           25      1.000
119        32410         86              9           95      0.905
120        33020         45              2           47      0.957
121        33030         49             18           67      0.731
122        33040         32             10           42      0.762
123        33320         15             11           26      0.577
124        33330         14              0           14      1.000
125        33340          5              1            6      0.833
126        33350          9              4           13      0.692
127        33360         22              2           24      0.917
128        33370          4              0            4      1.000
129        33380        135             15          150      0.900
130        33390          4              0            4      1.000
131        34010         21              9           30      0.700
132        34020        101             17          118      0.856
133        34030        185             16          201      0.920
134        34040         37             10           47      0.787
135        34050         26              1           27      0.963
136        34060         36              4           40      0.900
137        34070          2              1            3      0.667
138        34080         35              0           35      1.000
139        34310         28              3           31      0.903
140        34330         46              5           51      0.902
141        34340         64              7           71      0.901
142        34350          6              3            9      0.667
143        34360          3              1            4      0.750
144        34370         29              1           30      0.967
145        34380        101             16          117      0.863
146        35010         87             15          102      0.853
147        35020         92             16          108      0.852
148        35030          7              0            7      1.000
149        35040         29              3           32      0.906
150        35050         22              9           31      0.710
151        35060          2              0            2      1.000
152        35310         11              6           17      0.647
153        35320          6              2            8      0.750
154        35330         45              8           53      0.849
155        35340          1              0            1      1.000
156        35350         16              0           16      1.000
157        35360          9              4           13      0.692
158        35370         42              3           45      0.933
159        35380         59              2           61      0.967
160        36010         39              4           43      0.907
161        36020        252             79          331      0.761
162        36030         94             38          132      0.712
163        36040          6             13           19      0.316
164        36060          6              5           11      0.545
165        36310        135              2          137      0.985
166        36320         50              7           57      0.877
167        36330         44             16           60      0.733
168        36350          9              4           13      0.692
169        36360         18              3           21      0.857
170        36370          9              1           10      0.900
171        36390          9             11           20      0.450
172        36400          7              4           11      0.636
173        36410          4              0            4      1.000
174        36420          3              3            6      0.500
175        36430          2              0            2      1.000
176        36440          6              2            8      0.750
177        36450         52              0           52      1.000
178        36460         11             23           34      0.324
179        36470         40              0           40      1.000
180        36480         17              7           24      0.708
181        37010        138             42          180      0.767
182        37020        342             57          399      0.857
183        37030         11              0           11      1.000
184        37040         59             10           69      0.855
185        37050         15              4           19      0.789
186        37060         25              7           32      0.781
187        37070          6              3            9      0.667
188        37080          8              1            9      0.889
189        37090         47              4           51      0.922
190        37100          7              2            9      0.778
191        37310         10              1           11      0.909
192        37320          9              1           10      0.900
193        37330         27              6           33      0.818
194        37340          5              0            5      1.000
195        37350        113             11          124      0.911
196        37360         29              0           29      1.000
197        37370          1              0            1      1.000
198        37380          5              1            6      0.833
199        37390          1              2            3      0.333
200        37400          5              1            6      0.833
201        37410         12              4           16      0.750
202        37420         58              6           64      0.906
203        37430         14             42           56      0.250
204        38030         34              9           43      0.791
205        38050         97             40          137      0.708
206        38060         25              5           30      0.833
207        38070          4              9           13      0.308
208        38080         48              6           54      0.889
209        38090         86             32          118      0.729
210        38100         18              3           21      0.857
211        38110         20              8           28      0.714
212        38310          0              1            1      0.000
213        38320          8              0            8      1.000
214        38330          5              2            7      0.714
215        38340         14              1           15      0.933
216        38350         97             11          108      0.898
217        38360         55              6           61      0.902
218        38370         19              1           20      0.950
219        38380         15              1           16      0.938
220        38390         18              1           19      0.947
221        38400         15              3           18      0.833
222        39010         81            874          955      0.085
223        39020        109            825          934      0.117

## 22~24 전체 자동차 의존도 계산

In [ ]:
import pandas as pd

f_all = summary[summary['total_count'] >= 4].copy()
f_2022 = region_df_2022[region_df_2022['total_count'] >= 4].copy()
f_2023 = region_df_2023[region_df_2023['total_count'] >= 4].copy()

f_all = f_all.rename(columns=lambda x: f"all_{x}" if x != "region_code" else x)
f_2022 = f_2022.rename(columns=lambda x: f"y2022_{x}" if x != "region_code" else x)
f_2023 = f_2023.rename(columns=lambda x: f"y2023_{x}" if x != "region_code" else x)

merged = pd.merge(f_all, f_2022, on="region_code", how="outer")
merged = pd.merge(merged, f_2023, on="region_code", how="outer")

merged = merged.sort_values("region_code").reset_index(drop=True)

merged

,region_code,all_car_count,all_non_car_count,all_total_count,all_car_ratio,y2022_car_count,y2022_non_car_count,y2022_total_count,y2022_car_ratio,y2023_car_count,y2023_non_car_count,y2023_total_count,y2023_car_ratio
0,11010,0.0,17.0,17.0,0.000,1.0,9.0,10.0,0.100,17,57,74,0.230
1,11020,1.0,4.0,5.0,0.200,4.0,5.0,9.0,0.444,14,30,44,0.318
2,11030,0.0,4.0,4.0,0.000,NaN,NaN,NaN,NaN,10,15,25,0.400
3,11040,1.0,4.0,5.0,0.200,NaN,NaN,NaN,NaN,3,8,11,0.273
4,11050,0.0,4.0,4.0,0.000,NaN,NaN,NaN,NaN,2,12,14,0.143
5,11060,1.0,3.0,4.0,0.250,NaN,NaN,NaN,NaN,5,1,6,0.833
6,11090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3,5,0.400
7,11100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,8,11,0.273
8,11110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,7,0.429
9,11120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,7,0.429
10,11140,0.0,6.0,6.0,0.000,1.0,5.0,6.0,0.167,4,31,35,0.114
11,11160,3.0,1.0,4.0,0.750,NaN,NaN,NaN,NaN,2,6,8,0.250
12,11170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,4,4,0.000
13,11190,NaN,NaN,NaN,NaN,2.0,2.0,4.0,0.500,4,22,26,0.154
14,11210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6,12,0.500
15,11220,1.0,7.0,8.0,0.125,NaN,NaN,NaN,NaN,3,8,11,0.273
16,11230,0.0,13.0,13.0,0.000,5.0,10.0,15.0,0.333,18,38,56,0.321
17,11240,2.0,3.0,5.0,0.400,NaN,NaN,NaN,NaN,9,36,45,0.200
18,21010,2.0,2.0,4.0,0.500,NaN,NaN,NaN,NaN,34,19,53,0.642
19,21020,1.0,3.0,4.0,0.250,NaN,NaN,NaN,NaN,22,21,43,0.512
20,21030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,5,9,0.444
21,21040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,15,41,0.634
22,21050,1.0,4.0,5.0,0.200,4.0,3.0,7.0,0.571,11,7,18,0.611
23,21060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2,7,0.714
24,21070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,6,14,0.571
25,21090,5.0,15.0,20.0,0.250,8.0,9.0,17.0,0.471,134,70,204,0.657
26,21100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,6,11,0.455
27,21110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,4,0.250
28,21140,1.0,6.0,7.0,0.143,3.0,1.0,4.0,0.750,34,24,58,0.586
29,21310,6.0,3.0,9.0,0.667,2.0,4.0,6.0,0.333,37,14,51,0.725
30,22010,4.0,3.0,7.0,0.571,3.0,4.0,7.0,0.429,44,22,66,0.667
31,22020,4.0,1.0,5.0,0.800,NaN,NaN,NaN,NaN,23,8,31,0.742
32,22040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,5,0.600
33,22050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,4,0.750
34,22060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,0,17,1.000
35,22070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,4,15,0.733
36,22310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,0,7,1.000
37,23010,NaN,NaN,NaN,NaN,6.0,0.0,6.0,1.000,39,10,49,0.796
38,23040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,2,15,0.867
39,23050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,0,13,1.000
40,23060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,6,0.500
41,23080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,3,8,0.625
42,23310,NaN,NaN,NaN,NaN,3.0,1.0,4.0,0.750,75,4,79,0.949
43,23320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,1.000
44,24010,4.0,3.0,7.0,0.571,4.0,0.0,4.0,1.000,49,3,52,0.942
45,24020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2,12,0.833
46,24030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,1.000
47,24040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2,12,0.833
48,25010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,3,14,0.786
49,25020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,9,21,0.571
50,25030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,5,20,0.750
51,25040,6.0,3.0,9.0,0.667,3.0,4.0,7.0,0.429,32,8,40,0.800
52,25050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,2,11,0.818
53,26010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,1,14,0.929
54,26020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,4,16,0.750
55,26030,3.0,1.0,4.0,0.750,NaN,NaN,NaN,NaN,11,3,14,0.786
56,26310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,5,29,0.828
57,29010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,17,33,0.485
58,31010,12.0,6.0,18.0,0.667,5.0,2.0,7.0,0.714,43,28,71,0.606
59,31020,5.0,1.0,6.0,0.833,NaN,NaN,NaN,NaN,12,9,21,0.571
60,31030,0.0,4.0,4.0,0.000,4.0,2.0,6.0,0.667,5,10,15,0.333
61,31040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6,7,0.143
62,31050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,6,8,0.250
63,31070,NaN,NaN,NaN,NaN,1.0,3.0,4.0,0.250,8,4,12,0.667
64,31080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2,8,0.750
65,31090,1.0,3.0,4.0,0.250,3.0,1.0,4.0,0.750,14,3,17,0.824
66,31100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,11,35,0.686
67,31110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,6,13,0.538
68,31120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,4,0.500
69,31130,3.0,1.0,4.0,0.750,NaN,NaN,NaN,NaN,16,3,19,0.842
70,31140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3,5,0.400
71,31150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,5,14,0.643
72,31170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,0,10,1.000
73,31180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,11,0.909
74,31190,NaN,NaN,NaN,NaN,4.0,2.0,6.0,0.667,30,14,44,0.682
75,31200,4.0,2.0,6.0,0.667,4.0,1.0,5.0,0.800,58,7,65,0.892
76,31210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,2,15,0.867
77,31220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,1,16,0.938
78,31230,3.0,1.0,4.0,0.750,NaN,NaN,NaN,NaN,20,3,23,0.870
79,31240,3.0,1.0,4.0,0.750,4.0,0.0,4.0,1.000,68,9,77,0.883
80,31250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,6,31,0.806
81,31260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,3,19,0.842
82,31270,NaN,NaN,NaN,NaN,2.0,2.0,4.0,0.500,70,6,76,0.921
83,31280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,4,26,0.846
84,31350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,1,18,0.944
85,31370,8.0,2.0,10.0,0.800,NaN,NaN,NaN,NaN,171,20,191,0.895
86,31380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93,6,99,0.939
87,32010,6.0,5.0,11.0,0.545,7.0,3.0,10.0,0.700,85,19,104,0.817
88,32020,4.0,1.0,5.0,0.800,6.0,2.0,8.0,0.750,51,15,66,0.773
89,32030,10.0,9.0,19.0,0.526,29.0,14.0,43.0,0.674,272,78,350,0.777
90,32040,3.0,2.0,5.0,0.600,9.0,2.0,11.0,0.818,55,7,62,0.887
91,32050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,2,20,0.900
92,32060,9.0,6.0,15.0,0.600,17.0,8.0,25.0,0.680,221,29,250,0.884
93,32070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57,12,69,0.826
94,32310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,5,41,0.878
95,32320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,2,9,0.778
96,32330,NaN,NaN,NaN,NaN,4.0,0.0,4.0,1.000,20,3,23,0.870
97,32340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,7,37,0.811
98,32350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,6,33,0.818
99,32360,NaN,NaN,NaN,NaN,0.0,4.0,4.0,0.000,15,17,32,0.469
100,32390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,6,23,0.739
101,32400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,0,25,1.000
102,32410,11.0,4.0,15.0,0.733,NaN,NaN,NaN,NaN,86,9,95,0.905
103,33020,NaN,NaN,NaN,NaN,4.0,0.0,4.0,1.000,45,2,47,0.957
104,33030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49,18,67,0.731
105,33040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32,10,42,0.762
106,33320,2.0,3.0,5.0,0.400,2.0,2.0,4.0,0.500,15,11,26,0.577
107,33330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,0,14,1.000
108,33340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,1,6,0.833
109,33350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,4,13,0.692
110,33360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,2,24,0.917
111,33370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,1.000
112,33380,NaN,NaN,NaN,NaN,12.0,0.0,12.0,1.000,135,15,150,0.900
113,33390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,1.000
114,34010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,9,30,0.700
115,34020,8.0,5.0,13.0,0.615,9.0,0.0,9.0,1.000,101,17,118,0.856
116,34030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185,16,201,0.920
117,34040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,10,47,0.787
118,34050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,1,27,0.963
119,34060,NaN,NaN,NaN,NaN,4.0,1.0,5.0,0.800,36,4,40,0.900
120,34080,3.0,2.0,5.0,0.600,5.0,0.0,5.0,1.000,35,0,35,1.000
121,34310,NaN,NaN,NaN,NaN,3.0,1.0,4.0,0.750,28,3,31,0.903
122,34330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46,5,51,0.902
123,34340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64,7,71,0.901
124,34350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,3,9,0.667
125,34360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,4,0.750
126,34370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,1,30,0.967
127,34380,2.0,7.0,9.0,0.222,5.0,0.0,5.0,1.000,101,16,117,0.863
128,35010,8.0,5.0,13.0,0.615,6.0,3.0,9.0,0.667,87,15,102,0.853
129,35020,3.0,2.0,5.0,0.600,NaN,NaN,NaN,NaN,92,16,108,0.852
130,35030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,0,7,1.000
131,35040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,3,32,0.906
132,35050,6.0,2.0,8.0,0.750,NaN,NaN,NaN,NaN,22,9,31,0.710
133,35310,NaN,NaN,NaN,NaN,1.0,3.0,4.0,0.250,11,6,17,0.647
134,35320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2,8,0.750
135,35330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,8,53,0.849
136,35350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,0,16,1.000
137,35360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,4,13,0.692
138,35370,NaN,NaN,NaN,NaN,5.0,0.0,5.0,1.000,42,3,45,0.933
139,35380,5.0,7.0,12.0,0.417,6.0,0.0,6.0,1.000,59,2,61,0.967
140,36010,2.0,7.0,9.0,0.222,NaN,NaN,NaN,NaN,39,4,43,0.907
141,36020,4.0,4.0,8.0,0.500,19.0,13.0,32.0,0.594,252,79,331,0.761
142,36030,3.0,3.0,6.0,0.500,7.0,1.0,8.0,0.875,94,38,132,0.712
143,36040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,13,19,0.316
144,36060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,5,11,0.545
145,36310,4.0,3.0,7.0,0.571,10.0,0.0,10.0,1.000,135,2,137,0.985
146,36320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50,7,57,0.877
147,36330,4.0,3.0,7.0,0.571,NaN,NaN,NaN,NaN,44,16,60,0.733
148,36350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,4,13,0.692
149,36360,NaN,NaN,NaN,NaN,3.0,1.0,4.0,0.750,18,3,21,0.857
150,36370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,1,10,0.900
151,36390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,11,20,0.450
152,36400,2.0,2.0,4.0,0.500,NaN,NaN,NaN,NaN,7,4,11,0.636
153,36410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,4,1.000
154,36420,2.0,2.0,4.0,0.500,NaN,NaN,NaN,NaN,3,3,6,0.500
155,36440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2,8,0.750
156,36450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52,0,52,1.000
157,36460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,23,34,0.324
158,36470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,0,40,1.000
159,36480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,7,24,0.708
160,37010,7.0,16.0,23.0,0.304,8.0,0.0,8.0,1.000,138,42,180,0.767
161,37020,5.0,8.0,13.0,0.385,9.0,2.0,11.0,0.818,342,57,399,0.857
162,37030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,0,11,1.000
163,37040,1.0,3.0,4.0,0.250,NaN,NaN,NaN,NaN,59,10,69,0.855
164,37050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,4,19,0.789
165,37060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,7,32,0.781
166,37070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,3,9,0.667
167,37080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,1,9,0.889
168,37090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47,4,51,0.922
169,37100,3.0,3.0,6.0,0.500,NaN,NaN,NaN,NaN,7,2,9,0.778
170,37310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,11,0.909
171,37320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,1,10,0.900
172,37330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,6,33,0.818
173,37340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,0,5,1.000
174,37350,3.0,2.0,5.0,0.600,4.0,0.0,4.0,1.000,113,11,124,0.911
175,37360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,0,29,1.000
176,37380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,1,6,0.833
177,37400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,1,6,0.833
178,37410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,4,16,0.750
179,37420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,6,64,0.906
180,37430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,42,56,0.250
181,38030,0.0,4.0,4.0,0.000,NaN,NaN,NaN,NaN,34,9,43,0.791
182,38050,4.0,4.0,8.0,0.500,4.0,1.0,5.0,0.800,97,40,137,0.708
183,38060,2.0,2.0,4.0,0.500,NaN,NaN,NaN,NaN,25,5,30,0.833
184,38070,NaN,NaN,NaN,NaN,0.0,4.0,4.0,0.000,4,9,13,0.308
185,38080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48,6,54,0.889
186,38090,NaN,NaN,NaN,NaN,6.0,0.0,6.0,1.000,86,32,118,0.729
187,38100,4.0,1.0,5.0,0.800,NaN,NaN,NaN,NaN,18,3,21,0.857
188,38110,3.0,1.0,4.0,0.750,2.0,4.0,6.0,0.333,20,8,28,0.714
189,38320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,0,8,1.000
190,38330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2,7,0.714
191,38340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,1,15,0.933
192,38350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97,11,108,0.898
193,38360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55,6,61,0.902
194,38370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,1,20,0.950
195,38380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,1,16,0.938
196,38390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,1,19,0.947
197,38400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,3,18,0.833
198,39010,5.0,25.0,30.0,0.167,7.0,40.0,47.0,0.149,81,874,955,0.085
199,39020,4.0,33.0,37.0,0.108,5.0,30.0,35.0,0.143,109,825,934,0.117

In [ ]:
region_df_2024_2 = summary[summary['total_count'] > 5].reset_index(drop=True)
region_df_2022_2 = region_df_2022[region_df_2022['total_count'] > 5].reset_index(drop=True)
region_df_2023_2 = region_df_2023[region_df_2023['total_count'] > 5].reset_index(drop=True)

In [ ]:
top20_all = region_df_2024_2.sort_values("car_ratio", ascending=False).head(20).reset_index(drop=True)

top20_2022 = region_df_2022_2.sort_values("car_ratio", ascending=False).head(20).reset_index(drop=True)

top60_2023 = region_df_2023_2.sort_values("car_ratio", ascending=False).head(60).reset_index(drop=True)

top20_all
top20_2022
top60_2023

    region_code  car_count  non_car_count  total_count  car_ratio
0         22310          7              0            7      1.000
1         22060         17              0           17      1.000
2         23050         13              0           13      1.000
3         37030         11              0           11      1.000
4         36450         52              0           52      1.000
5         34080         35              0           35      1.000
6         32400         25              0           25      1.000
7         33330         14              0           14      1.000
8         35030          7              0            7      1.000
9         31170         10              0           10      1.000
10        35350         16              0           16      1.000
11        37360         29              0           29      1.000
12        38320          8              0            8      1.000
13        36470         40              0           40      1.000
14        36310        135              2          137      0.985
15        35380         59              2           61      0.967
16        34370         29              1           30      0.967
17        34050         26              1           27      0.963
18        33020         45              2           47      0.957
19        38370         19              1           20      0.950
20        23310         75              4           79      0.949
21        38390         18              1           19      0.947
22        31350         17              1           18      0.944
23        24010         49              3           52      0.942
24        31380         93              6           99      0.939
25        31220         15              1           16      0.938
26        38380         15              1           16      0.938
27        38340         14              1           15      0.933
28        35370         42              3           45      0.933
29        26010         13              1           14      0.929
30        37090         47              4           51      0.922
31        31270         70              6           76      0.921
32        34030        185             16          201      0.920
33        33360         22              2           24      0.917
34        37350        113             11          124      0.911
35        37310         10              1           11      0.909
36        31180         10              1           11      0.909
37        36010         39              4           43      0.907
38        35040         29              3           32      0.906
39        37420         58              6           64      0.906
40        32410         86              9           95      0.905
41        34310         28              3           31      0.903
42        38360         55              6           61      0.902
43        34330         46              5           51      0.902
44        34340         64              7           71      0.901
45        34060         36              4           40      0.900
46        37320          9              1           10      0.900
47        32050         18              2           20      0.900
48        33380        135             15          150      0.900
49        36370          9              1           10      0.900
50        38350         97             11          108      0.898
51        31370        171             20          191      0.895
52        31200         58              7           65      0.892
53        38080         48              6           54      0.889
54        37080          8              1            9      0.889
55        32040         55              7           62      0.887
56        32060        221             29          250      0.884
57        31240         68              9           77      0.883
58        32310         36              5           41      0.878
59        36320         50              7           57      0.877

In [ ]:
import pandas as pd

df_all = pd.concat([
    region_df_2024_2,
    region_df_2022_2,
    region_df_2023_2
], ignore_index=True)

merged = df_all.groupby('region_code', as_index=False).agg({
    'car_count': 'sum',
    'non_car_count': 'sum',
    'total_count': 'sum'
})
merged['car_ratio'] = merged['car_count'] / merged['total_count']
merged = merged.sort_values('region_code').reset_index(drop=True)

merged

     region_code  car_count  non_car_count  total_count  car_ratio
0          11010         18             83          101   0.178218
1          11020         18             35           53   0.339623
2          11030         10             15           25   0.400000
3          11040          3              8           11   0.272727
4          11050          2             12           14   0.142857
5          11060          5              1            6   0.833333
6          11100          3              8           11   0.272727
7          11110          3              4            7   0.428571
8          11120          3              4            7   0.428571
9          11140          5             42           47   0.106383
10         11160          2              6            8   0.250000
11         11190          4             22           26   0.153846
12         11210          6              6           12   0.500000
13         11220          4             15           19   0.210526
14         11230         23             61           84   0.273810
15         11240          9             36           45   0.200000
16         21010         34             19           53   0.641509
17         21020         22             21           43   0.511628
18         21030          4              5            9   0.444444
19         21040         26             15           41   0.634146
20         21050         15             10           25   0.600000
21         21060          5              2            7   0.714286
22         21070          8              6           14   0.571429
23         21090        147             94          241   0.609959
24         21100          5              6           11   0.454545
25         21140         35             30           65   0.538462
26         21310         45             21           66   0.681818
27         22010         51             29           80   0.637500
28         22020         23              8           31   0.741935
29         22060         17              0           17   1.000000
30         22070         11              4           15   0.733333
31         22310          7              0            7   1.000000
32         23010         45             10           55   0.818182
33         23040         13              2           15   0.866667
34         23050         13              0           13   1.000000
35         23060          3              3            6   0.500000
36         23080          5              3            8   0.625000
37         23310         75              4           79   0.949367
38         24010         53              6           59   0.898305
39         24020         10              2           12   0.833333
40         24040         10              2           12   0.833333
41         25010         11              3           14   0.785714
42         25020         12              9           21   0.571429
43         25030         15              5           20   0.750000
44         25040         41             15           56   0.732143
45         25050          9              2           11   0.818182
46         26010         13              1           14   0.928571
47         26020         12              4           16   0.750000
48         26030         11              3           14   0.785714
49         26310         24              5           29   0.827586
50         29010         16             17           33   0.484848
51         31010         60             36           96   0.625000
52         31020         17             10           27   0.629630
53         31030          9             12           21   0.428571
54         31040          1              6            7   0.142857
55         31050          2              6            8   0.250000
56         31070          8              4           12   0.666667
57         31080          6              2            8   0.750000
58         31090         14              3           17   0.823529
59         31100         24             11           35   0.685714
60         31110          7              6           13   0.538462
61         31130         16              3           19   0.842105
62         31150          9              5           14   0.642857
63         31170         10              0           10   1.000000
64         31180         10              1           11   0.909091
65         31190         34             16           50   0.680000
66         31200         62              9           71   0.873239
67         31210         13              2           15   0.866667
68         31220         15              1           16   0.937500
69         31230         20              3           23   0.869565
70         31240         68              9           77   0.883117
71         31250         25              6           31   0.806452
72         31260         16              3           19   0.842105
73         31270         70              6           76   0.921053
74         31280         22              4           26   0.846154
75         31350         17              1           18   0.944444
76         31370        179             22          201   0.890547
77         31380         93              6           99   0.939394
78         32010         98             27          125   0.784000
79         32020         57             17           74   0.770270
80         32030        311            101          412   0.754854
81         32040         64              9           73   0.876712
82         32050         18              2           20   0.900000
83         32060        247             43          290   0.851724
84         32070         57             12           69   0.826087
85         32310         36              5           41   0.878049
86         32320          7              2            9   0.777778
87         32330         20              3           23   0.869565
88         32340         30              7           37   0.810811
89         32350         27              6           33   0.818182
90         32360         15             17           32   0.468750
91         32390         17              6           23   0.739130
92         32400         25              0           25   1.000000
93         32410         97             13          110   0.881818
94         33020         45              2           47   0.957447
95         33030         49             18           67   0.731343
96         33040         32             10           42   0.761905
97         33320         15             11           26   0.576923
98         33330         14              0           14   1.000000
99         33340          5              1            6   0.833333
100        33350          9              4           13   0.692308
101        33360         22              2           24   0.916667
102        33380        147             15          162   0.907407
103        34010         21              9           30   0.700000
104        34020        118             22          140   0.842857
105        34030        185             16          201   0.920398
106        34040         37             10           47   0.787234
107        34050         26              1           27   0.962963
108        34060         36              4           40   0.900000
109        34080         35              0           35   1.000000
110        34310         28              3           31   0.903226
111        34330         46              5           51   0.901961
112        34340         64              7           71   0.901408
113        34350          6              3            9   0.666667
114        34370         29              1           30   0.966667
115        34380        103             23          126   0.817460
116        35010        101             23          124   0.814516
117        35020         92             16          108   0.851852
118        35030          7              0            7   1.000000
119        35040         29              3           32   0.906250
120        35050         28             11           39   0.717949
121        35310         11              6           17   0.647059
122        35320          6              2            8   0.750000
123        35330         45              8           53   0.849057
124        35350         16              0           16   1.000000
125        35360          9              4           13   0.692308
126        35370         42              3           45   0.933333
127        35380         70              9           79   0.886076
128        36010         41             11           52   0.788462
129        36020        275             96          371   0.741240
130        36030        104             42          146   0.712329
131        36040          6             13           19   0.315789
132        36060          6              5           11   0.545455
133        36310        149              5          154   0.967532
134        36320         50              7           57   0.877193
135        36330         48             19           67   0.716418
136        36350          9              4           13   0.692308
137        36360         18              3           21   0.857143
138        36370          9              1           10   0.900000
139        36390          9             11           20   0.450000
140        36400          7              4           11   0.636364
141        36420          3              3            6   0.500000
142        36440          6              2            8   0.750000
143        36450         52              0           52   1.000000
144        36460         11             23           34   0.323529
145        36470         40              0           40   1.000000
146        36480         17              7           24   0.708333
147        37010        153             58          211   0.725118
148        37020        356             67          423   0.841608
149        37030         11              0           11   1.000000
150        37040         59             10           69   0.855072
151        37050         15              4           19   0.789474
152        37060         25              7           32   0.781250
153        37070          6              3            9   0.666667
154        37080          8              1            9   0.888889
155        37090         47              4           51   0.921569
156        37100         10              5           15   0.666667
157        37310         10              1           11   0.909091
158        37320          9              1           10   0.900000
159        37330         27              6           33   0.818182
160        37350        113             11          124   0.911290
161        37360         29              0           29   1.000000
162        37380          5              1            6   0.833333
163        37400          5              1            6   0.833333
164        37410         12              4           16   0.750000
165        37420         58              6           64   0.906250
166        37430         14             42           56   0.250000
167        38030         34              9           43   0.790698
168        38050        101             44          145   0.696552
169        38060         25              5           30   0.833333
170        38070          4              9           13   0.307692
171        38080         48              6           54   0.888889
172        38090         92             32          124   0.741935
173        38100         18              3           21   0.857143
174        38110         22             12           34   0.647059
175        38320          8              0            8   1.000000
176        38330          5              2            7   0.714286
177        38340         14              1           15   0.933333
178        38350         97             11          108   0.898148
179        38360         55              6           61   0.901639
180        38370         19              1           20   0.950000
181        38380         15              1           16   0.937500
182        38390         18              1           19   0.947368
183        38400         15              3           18   0.833333
184        39010         93            939         1032   0.090116
185        39020        118            888         1006   0.117296

In [ ]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   region_code    186 non-null    int64
 1   car_count      186 non-null    int64
 2   non_car_count  186 non-null    int64
 3   total_count    186 non-null    int64
 4   car_ratio      186 non-null    float64
dtypes: float64(1), int64(4)
memory usage: 7.4 KB

In [ ]:
merged = merged.sort_values("car_ratio", ascending=False).head(47).reset_index(drop=True)
merged

    region_code  car_count  non_car_count  total_count  car_ratio
0         22310          7              0            7   1.000000
1         22060         17              0           17   1.000000
2         23050         13              0           13   1.000000
3         37030         11              0           11   1.000000
4         36450         52              0           52   1.000000
5         34080         35              0           35   1.000000
6         32400         25              0           25   1.000000
7         33330         14              0           14   1.000000
8         35030          7              0            7   1.000000
9         31170         10              0           10   1.000000
10        35350         16              0           16   1.000000
11        37360         29              0           29   1.000000
12        38320          8              0            8   1.000000
13        36470         40              0           40   1.000000
14        36310        149              5          154   0.967532
15        34370         29              1           30   0.966667
16        34050         26              1           27   0.962963
17        33020         45              2           47   0.957447
18        38370         19              1           20   0.950000
19        23310         75              4           79   0.949367
20        38390         18              1           19   0.947368
21        31350         17              1           18   0.944444
22        31380         93              6           99   0.939394
23        31220         15              1           16   0.937500
24        38380         15              1           16   0.937500
25        38340         14              1           15   0.933333
26        35370         42              3           45   0.933333
27        26010         13              1           14   0.928571
28        37090         47              4           51   0.921569
29        31270         70              6           76   0.921053
30        34030        185             16          201   0.920398
31        33360         22              2           24   0.916667
32        37350        113             11          124   0.911290
33        31180         10              1           11   0.909091
34        37310         10              1           11   0.909091
35        33380        147             15          162   0.907407
36        35040         29              3           32   0.906250
37        37420         58              6           64   0.906250
38        34310         28              3           31   0.903226
39        34330         46              5           51   0.901961
40        38360         55              6           61   0.901639
41        34340         64              7           71   0.901408
42        34060         36              4           40   0.900000
43        37320          9              1           10   0.900000
44        32050         18              2           20   0.900000
45        36370          9              1           10   0.900000
46        24010         53              6           59   0.898305

In [ ]:
merged['SIDO_code'] = merged['region_code']//1000

merged['SIDO_code'].astype(object)

merged['SIDO_code'].value_counts()

SIDO_code
34    8
37    7
31    6
38    6
35    4
33    4
36    4
23    2
22    2
32    2
26    1
24    1
Name: count, dtype: int64

In [ ]:
merged

    region_code  car_count  non_car_count  total_count  car_ratio  SIDO_code
0         22310          7              0            7   1.000000         22
1         22060         17              0           17   1.000000         22
2         23050         13              0           13   1.000000         23
3         37030         11              0           11   1.000000         37
4         36450         52              0           52   1.000000         36
5         34080         35              0           35   1.000000         34
6         32400         25              0           25   1.000000         32
7         33330         14              0           14   1.000000         33
8         35030          7              0            7   1.000000         35
9         31170         10              0           10   1.000000         31
10        35350         16              0           16   1.000000         35
11        37360         29              0           29   1.000000         37
12        38320          8              0            8   1.000000         38
13        36470         40              0           40   1.000000         36
14        36310        149              5          154   0.967532         36
15        34370         29              1           30   0.966667         34
16        34050         26              1           27   0.962963         34
17        33020         45              2           47   0.957447         33
18        38370         19              1           20   0.950000         38
19        23310         75              4           79   0.949367         23
20        38390         18              1           19   0.947368         38
21        31350         17              1           18   0.944444         31
22        31380         93              6           99   0.939394         31
23        31220         15              1           16   0.937500         31
24        38380         15              1           16   0.937500         38
25        38340         14              1           15   0.933333         38
26        35370         42              3           45   0.933333         35
27        26010         13              1           14   0.928571         26
28        37090         47              4           51   0.921569         37
29        31270         70              6           76   0.921053         31
30        34030        185             16          201   0.920398         34
31        33360         22              2           24   0.916667         33
32        37350        113             11          124   0.911290         37
33        31180         10              1           11   0.909091         31
34        37310         10              1           11   0.909091         37
35        33380        147             15          162   0.907407         33
36        35040         29              3           32   0.906250         35
37        37420         58              6           64   0.906250         37
38        34310         28              3           31   0.903226         34
39        34330         46              5           51   0.901961         34
40        38360         55              6           61   0.901639         38
41        34340         64              7           71   0.901408         34
42        34060         36              4           40   0.900000         34
43        37320          9              1           10   0.900000         37
44        32050         18              2           20   0.900000         32
45        36370          9              1           10   0.900000         36
46        24010         53              6           59   0.898305         24

In [ ]:
merged.to_csv('car dependency.csv', index=False)

In [ ]:
from google.colab import files
files.download('car dependency.csv')